version: '3.8'

services:
  marathon-tracker:
    container_name: marathon-tracker
    build: .
    image: wewerew/marathon-tracker
    ports:
      - "8080:80" # Change 8080 to whatever port you want to access the app on
    environment:
      - VITE_FIREBASE_API_KEY
      - VITE_FIREBASE_AUTH_DOMAIN
      - VITE_FIREBASE_PROJECT_ID
      - VITE_FIREBASE_STORAGE_BUCKET
      - VITE_FIREBASE_MESSAGING_SENDER_ID
      - VITE_FIREBASE_APP_ID
      - VITE_GEMINI_API_KEY
    restart: unless-stopped
